ambassador:
  rollouts:
    annotations:
      getambassador.io/rolloutId: d7f79f3c-a7db-4ad3-89a2-c4f5ea630ceb
    image:
      repository: docker.io/datawire/quote
      tag: 0.5.0
    replicas: 2
    steps:
    - setWeight: 30
    - pause:
        duration: 80
    - setWeight: 60
    - pause:
        duration: 80
    - setWeight: 90
    - pause:
        duration: 80
